DESCRIBE HISTORY employees
SELECT * FROM employees VERSION AS OF 1
SELECT * FROM employees@v1
DELETE FROM employees
SELECT * FROM employees
RESTORE TABLE employees TO VERSION AS OF 2
SELECT * FROM employees
DESCRIBE HISTORY employees
OPTIMIZE employees
ZORDER BY iD
DESCRIBE DETAIL employees
VACUUM employees RETAIN 0 HOURS
DROP TABLE employees
SELECT * FROM employees
